### PR TITLE
Update abs.adoc

### PR DESCRIPTION
**Pull request by animeshsrivastava24**
Issue #604 
@per1234  Please have a look. We can add further details to a mathematical section for more description.

### CODE REVIEW

**Comment by animeshsrivastava24** [comment]
@per1234  thank you so much for the suggestions, yes definitely we can create the images. I will create the samples and will update it to you soon.

**Comment by animeshsrivastava24** [comment]
@per1234  To reference the issue, If we work to create images from our own to reference the issue, what guidelines should be followed.

**Comment by per1234** [comment]
@animeshsrivastava24 I'm not sure. I'm intrigued by the idea of using graphs to make documentation more understandable. For me, the text is enough, but I know that some people are visual learners.

Maybe @robsoncouto and @SeppPenner have some opinions on this proposal they can share.

**Comment by SeppPenner** [comment]
I agree with @per1234 that we need the image locally if we want to use an image. In general, I'm not a fan of putting a lot of pictures to the documentation but in this case it might make sense.

@animeshsrivastava24 I don't believe that there are some hard guidelines for images. I would reproduce the image https://www.mathsisfun.com/sets/images/function-absolute.svg but add some scale on the axes, too. I would leave out the yellow square,  too. And add some description for the image. I mean, for me it's clear what `abs()` does, but for beginners the image might help.

**Comment by animeshsrivastava24** [comment]
@SeppPenner Thanks a lot for the valuable suggestions, sure, I'll work to create it locally. Also, if we want we can create a separate page for graphs and provide links to it in the documentation. I guess it will be easy to preserve the same standard format of Documentation everywhere and it will also guide the beginners with information they need.

**Comment by robsoncouto** [comment]
Sorry for not replying to this before.

Adding graphs to the documentation would be a huge change, but I don't know if it would would be worth it. In my understanding, only a few people would benefit from it, while for the rest it may be redundant.

I think that uniformity may be a problem, so if images are to be used, there should be guidelines on how to create them, like the size, colors, etc. Also, If the images contain text, they may not be easily reused in the other translated references without editing. 

Moreover, we can not just add pictures to the pages without context, but describing the picture (maths or electronics, for example) may not be the point of this documentation.

**Comment by animeshsrivastava24** [comment]
Yes, I am too thinking about the method to include the graph with proper guidelines, and keeping in view the translation process, we can think of not including text on images for easy access and reproducibility across various language platforms. 

> I think that uniformity may be a problem, so if images are to be used, there should be guidelines on how to create them, like the size, colors, etc. Also, If the images contain text, they may not be easily reused in the other translated references without editing.
> 
> Moreover, we can not just add pictures to the pages without context, but describing the picture (maths or electronics, for example) may not be the point of this documentation.

So, before creating graphs, should I propose guidelines and method to include the graphs (Keeping in view the ideas of @SeppPenner ). Definitely, we all agree that the graphs should not be included in the present documentation to ensure uniformity across all the pages. So should we have a link to an image section (created as per requirement)?
@per1234 Please guide.

**Comment by per1234** [comment]
Thanks so much for your pull request @animeshsrivastava24. Since the PR's current approach of using a "hotlinked" image from an external source is not appropriate, I will close this.

**Pull request closed without merging**
