### PR TITLE
Update SPI.adoc

### PR DESCRIPTION
**Pull request by John-Karatka**
Added endTransaction() link to function section.

### CODE REVIEW

**Comment by John-Karatka** [comment]
Signed CLA

**Review by John-Karatka — COMMENTED** [review]
Signed CLA

**Review by per1234 — CHANGES_REQUESTED** [review]
I think it will be best to place the link on the line after the link for the `beginTransaction` reference page, as the order was in the original SPI library reference before the loss of the link during the migration.

You can see how it used to look here on the Wayback Machine snapshot:

https://web.archive.org/web/20220120162953/https://www.arduino.cc/en/Reference/SPI

image

**Review by per1234 — APPROVED** [review]
Thanks so much for fixing this serious omission @John-Karatka!

**Pull request merged**
