### PR TITLE
Typo fixed else.adoc

### PR DESCRIPTION
**Pull request by animeshsrivastava24**

### CODE REVIEW

**Comment by smellai** [comment]
I think the subject is "An unlimited number" (singular)

**Comment by animeshsrivastava24** [comment]
The verb "is" doesn't seem to agree with subject "branches"

**Comment by animeshsrivastava24** [comment]
@per1234 Eagerly waiting for your feedback over this discussion.

**Comment by per1234** [comment]
I wasn't 100% sure, so I asked my Mom, who's an author.

In the sentence, "an unlimited number of" is a variation of the phrase "a number of". Although the word "number" is singular, this phrase is plural, so the verb should also be plural (are). Thus, the correct sentence is:

>An unlimited number of such `else if` branches are allowed.

Reference:
https://www.dailywritingtips.com/is-number-singular-or-plural/

**Pull request merged**
