### PR TITLE
Removed ` before myString2 and used more suitable word.

### PR DESCRIPTION
**Pull request by abdullah-1307**

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
Hi @abdullah-1307. Thanks for taking the time to submit this correction.

Please follow the format established in the other String reference pages.

If you use this page as a reference:
https://raw.githubusercontent.com/arduino/reference-en/master/Language/Variables/Data%20Types/String/Operators/comparison.adoc

```asciidoc
=== Parameters
`myString1`: a String variable. +
`myString2`: a String variable.
```
You can see that the bad formatting is caused by a missing `` ` `` after `myString1`

**Comment by per1234** [comment]
Hi @abdullah-1307. I wanted to check back in with you. If you will update the pull request according to the instructions I provided above I will be happy to merge this important correction.

**Comment by per1234** [comment]
Hi @abdullah-1307. I wanted to check back in with you. If you will update the pull request according to the instructions I provided above I will be happy to merge this important correction.

**Comment by per1234** [comment]
Hi @abdullah-1307. I wanted to check back in with you. If you will update the pull request according to the instructions I provided above I will be happy to merge this important correction.

**Comment by abdullah-1307** [comment]
@per1234.

**Comment by abdullah-1307** [comment]
dear per1234,
can you please let me know what else you want me to do for this change to
occur?

Thanks

**Review by abdullah-1307 — COMMENTED** [review]
Yes, i guess this seems ok to go with.

**Comment by abdullah-1307** [comment]
sorry for bothering you, can you please let me know how to update the pull request and where to? im new to github

**Comment by abdullah-1307** [comment]
dear @per1234 , kindly check and let me know now.

**Review by per1234 — APPROVED** [review]
Thanks so much @abdullah-1307!

**Comment by abdullah-1307** [comment]
Thanks to you

**Pull request merged**
