### PR TITLE
 analogWrite.adoc

### PR DESCRIPTION
**Pull request by cm7799**

### CODE REVIEW

**Comment by robsoncouto** [comment]
Hey @smellai, these pull requests (#465 and #464 as well) have links to youtube videos. I am guessing these are not allowed (since almost all current links reference only other pages of the reference or arduino.cc tutorials). Also, I think that to merge this kind of link into the documentation one would have to watch the videos thoroughly (one of them is 31 minutes, for example).

The README has nothing on this, although one of the samples shows how to embed a video into the page.  

Could you confirm or assign someone, please?  
Thanks!

**Comment by smellai** [comment]
@cm7799, we appreciate the work you've been doing for the Arduino community related to the Documentation. However, you included some links to video tutorials on YouTube. While they may be useful, our policy is not to allow links to external resources that we can't control or maintain. Therefore, we cannot approve this pull request. We hope you won't be too disappointed by this, though, and will continue to contribute to the Documentation.

**Comment by cm7799** [comment]
Ya ,I accept it. Actually i thought it might help others in more detail .
but yes according to your point of veiw you are right .

**Comment by PaulStoffregen** [comment]
Oh if only Arduino had a debouncing feature built in.  This is one of the very common problems users face.  It'd be a real shame to not even advise users due to a rigid policy.

**Pull request closed without merging**
