### PR TITLE
Fixed code syntax related typo print.adoc

### PR DESCRIPTION
**Pull request by animeshsrivastava24**
Fixed code syntax related typo

### CODE REVIEW

**Comment by per1234** [comment]
Thank you!

**Comment by SeppPenner** [comment]
@per1234 Doesn't `Serial` need to be cursive in this case, too?

**Comment by per1234** [comment]
@SeppPenner yes, since by "Serial" the "You can pass flash-memory based strings to `Serial.print()`" text is referring to any HardwareSerial object, it should be in italics.

**Comment by SeppPenner** [comment]
@per1234 Every occurance in the file or only in this case?

**Comment by per1234** [comment]
It should also be done in in the "Notes and Warnings" section here:
>For information on the asyncronicity of `Serial.print()`

As to the lists in the "Description" section, one could argue it is fine as-is because it's example code specifically using the `Serial` object. Or you could say this is demonstrating the various syntax of the function, in which case the italics would be better. If you want to submit a PR to fix this, I'll leave it up to you to decide.

**Comment by SeppPenner** [comment]
> As to the lists in the "Description" section, one could argue it is fine as-is because it's example code specifically using the Serial object. Or you could say this is demonstrating the various syntax of the function, in which case the italics would be better.

I agree with you. There are multiple possible interpretations. The PR makes all of them italic because it's more consistent. I understand the point that it shows example code as well, however.

**Pull request merged**
