### PR TITLE
Fix misspellings in headings

### PR DESCRIPTION
**Pull request by mattborja**
Headings fixed:
- "Syntax"
- "Parameters"

### CODE REVIEW

**Review by per1234 — APPROVED** [review]
Thanks @mattborja!

**Comment by matthijskooijman** [comment]
I was going to leave an approving review, but seems I'm too late :-p

Thanks for the lightning quick action, both!

**Comment by mattborja** [comment]
@matthijskooijman In fairness, 2 bytes of change doesn't take long to commit (or review for that matter) :P

**Comment by matthijskooijman** [comment]
> @matthijskooijman In fairness, 2 bytes of change doesn't take too long to commit (or review for that matter) :P

Well, I think I might have had a couple of those bytes that took a *whole* lot longer in other projects, so no guarantees :-p

**Pull request merged**
