### PR TITLE
Specified Even and Odd Parity in begin.adoc

### PR DESCRIPTION
**Pull request by animeshsrivastava24**
Specified Even and Odd Parity
Reference : #612

### CODE REVIEW

**Comment by animeshsrivastava24** [comment]
@per1234  Please review.

**Comment by per1234** [comment]
I left this one open for a while to give any interested parties an opportunity to provide feedback, but I guess it's been long enough now. Thanks!

**Comment by animeshsrivastava24** [comment]
Thank you so much for the reply. I definitely understand your point.

I've a small question- I was little curious to know about Arduino Bot. I usually see messages with it's description in mails.
I tried searching it on internet but was not able find any relevant information.

**Comment by per1234** [comment]
@ArduinoBot is a GitHub account used by Arduino to interface automated processes with GitHub.

In this repository, ArduinoBot creates an issue report when broken links are found in the Language Reference content.

In the Language Reference translation repositories, ArduinoBot creates an issue report every time a pull request is merged in the arduino/reference-en repository. These issue reports act as a "to-do" list for the work that needs to be done to keep the translation repository content in sync with the English language content. You may have noticed that ArduinoBot only started creating these issues in the arduino/reference-en repository in the last two days, even though there were many other pull requests merged in the arduino/reference-en repository since the time the arduino/reference-hi repository was created. This is because it took some time to get ArduinoBot configured for the new repository. We'll need to be careful to make sure that all the previous pull requests merged in the arduino/reference-en repository, for which there were no automated issue reports, get synced over to the arduino/reference-hi repository as well.

In other Arduino repositories, ArduinoBot can be asked by the Arduino developers to do test builds and it will then comment with links to the build files for human beta testers to download.

**Comment by animeshsrivastava24** [comment]
Wow, I'm amazed by the work done by the bot. Yes, I started recieving mails from it recently so I became curious about it.
Thanks a lot for this information, it is very valuable and helpful for me to understand about the working of the bot.

**Pull request merged**
