### PR TITLE
Update analogWrite doc

### PR DESCRIPTION
**Pull request by katerss1**
You need to call pinMode() before calling analogWrite();

### CODE REVIEW

**Comment by kengdahl** [comment]
If nobody objects I will merge this.

**Comment by per1234** [comment]
@katerss1 @kengdahl which board did you find this was necessary for?

I know that, for Arduino AVR Boards, the previous documentation was correct:
https://github.com/arduino/ArduinoCore-avr/blob/1.8.3/cores/arduino/wiring_analog.c#L108-L111
```
	// writing with them.  Also, make sure the pin is in output mode
	// for consistenty with Wiring, which doesn't require a pinMode
	// call for the analog output pins.
	pinMode(pin, OUTPUT);
```
I haven't looked at other official boards platforms though.

**Comment by kengdahl** [comment]
@per1234 
Without the `pinMode();` it is not working properly on the MKR boards. So there is an inconsistency between our boards.

**Comment by kengdahl** [comment]
@per1234 did some research and:
Is it necessary to call `pinMode(pin, OUTPUT)` when using `analogWrite`()?

- ARC32 (Arduino 101): no
- AVR (Uno): no
- Mbed (Nano 33 BLE): no
- Mbed (Portenta H7 (M7 core)): no
- Mbed (Portenta H7 (M4 core)): no
- megaAVR (Nano Every): no
- SAM (Due): no
- SAMD (MKR WiFi 1010): no

The test sketch:
```
void setup() {
  analogWrite(3, 125);
}
void loop() {}
```
So all the official Arduino boards platforms behave consistently in regards to not needing to set the pin mode to `OUTPUT `when using `analogWrite()` and the documentation is fine as it is now in this regard.

**Pull request merged**
