### PR TITLE
Open external See also links in new window/tab

### PR DESCRIPTION
**Pull request by per1234**
According to the reference example:
https://github.com/arduino/reference-en/blob/afde77c8537eb03d60ef066011bdbd425722c90a/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Single_Entity.adoc#L127-L128

### CODE REVIEW

**Comment by robsoncouto** [comment]
Hey @per1234, I am assuming you are now part of Arduino and in charge of this repo as well others. 
So I guess you could merge these up directly (Good stuff btw).  But If you want my second opinion you can just tell me or tag me up, no problem.
I will be focusing on the issues on the Portuguese reference repo for a while, as it received a lot of automatic issues recently.

**Comment by per1234** [comment]
@robsoncouto You're correct that I was recently given push access to this repository. However, I've now been informed that there is an unwritten rule that the author of a PR is not allowed to merge their own PR. From now on, I can merge PRs submitted by other people (and will try to take an active role in doing so), but I can not merge any of the PRs I submit.

I am looking forward to continuing with ongoing work on the reference but it becomes more difficult and inefficient (due to wasting time resolving merge conflicts) as multiple PRs impact on the same files. So getting some of my PRs merged is helpful to progress.

If you have time to review and merge (or request changes or reject) any of my PRs, that is much appreciated. If not, I completely understand and will have to patiently wait for an Arduino employee to get the time to do so. 

I'm going to try to help out in the translation repositories with the changes that don't require any language skills, but there will still be a lot of things that I can't do due to my lack of fluency in each language. I hope that this work will be worthwhile in the end with the result of a better Language Reference.

Thanks so much for the excellent work you have done in the reference-pt and this repository. It's very impressive!

**Comment by per1234** [comment]
By the way, I don't think you should assume that the "no merging your own PR" rule I mentioned applies to the reference-pt repository.

I can't make official policy decisions for Arduino, but I think they would be crazy to put such a limit on the work in the translation repositories.

**Comment by robsoncouto** [comment]
Thanks for the kind words, per. 

I was unaware of the "no merging your own PR" rule.  Thanks for clarifying.
I have seen that you have done a lot of work on the reference-pt repo already, much appreciated. It will speed up things a lot. Your work on the repositories I have seen is remarkable.
I will first have a look at the PRs you sent to the reference-pt repo, to catch up a little with this one and then I hope I can have a look at the ones here too.

**Comment by per1234** [comment]
I went through all the open issues in the reference-pt repository and submitted PRs to fix all the ones that didn't require Portuguese. I also commented on all the issues that have already been fixed by existing commits in the repository.

If you run into any merge conflicts in my pull requests, please feel free to just leave a comment in the PR requesting that I fix the conflict. I'm pretty good at doing so and it only takes a couple minutes. I'd rather that you spend your limited time on the things you're specially qualified for.

**Comment by robsoncouto** [comment]
> I went through all the open issues in the reference-pt repository and submitted PRs to fix all the ones that didn't require Portuguese. I also commented on all the issues that have already been fixed by existing commits in the repository.

Thankfully there were no conflicts, but I left some PRs unaccepted with comments about them.

> If you run into any merge conflicts in my pull requests, please feel free to just leave a comment in the PR requesting that I fix the conflict. I'm pretty good at doing so and it only takes a couple minutes. I'd rather that you spend your limited time on the things you're specially qualified for.

Great, I will have that in mind!

**Comment by robsoncouto** [comment]
Merged. Thanks, per

**Pull request merged**
